---
monitors:
  cat_production:
    name: CAT API
    target: https://cat.nlsn-eng-ops.com
    label: production

  cat_dns_production:
    name: CAT DNS
    protocol: dns
    expectation: secure-eu.imrworldwide.com
    target: 52.207.62.137
    label: production
    interval: 10s

  websocket_service_production:
    name: Websocket Service
    target: https://websocket-service-api.nlsn-eng-ops.com/health
    label: production

  dog_api_production:
    name: DOG API
    target: https://dog-api.nlsn-eng-ops.com/ping
    label: production

  dog_ui_production:
    name: DOG UI
    target: https://dog.nlsn-eng-ops.com
    label: production

  bee_ui_production:
    name: BEE UI
    target: https://bee.nlsn-eng-ops.com
    label: production

  bee_api_production:
    name: BEE API
    target: https://bee-api.nlsn-eng-ops.com/ping
    label: production
